

############## HTTP SERVER ##############
server {
    listen 80;
    listen [::]:80;
    server_name docs.tokopawon.id;

    # Allow certbot renew via webroot
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    
    location /toko-pawon/v1 {
        alias /var/www/toko-pawon/docs/public;
    }

    location / {
        root /var/www/toko-pawon/docs/public;
    }

}

############## HTTPS SERVER (uncomment when SSL is ready) ##############
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name docs.tokopawon.id;

    client_max_body_size 1G;  # MinIO needs larger upload limits

    ssl_certificate /etc/letsencrypt/live/docs.tokopawon.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/docs.tokopawon.id/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location = / {
      return 301 /v1;
  }

    location /v1 {
        alias /var/www/toko-pawon/docs/public;
    }
}