

############## HTTP SERVER ##############
server {
    listen 80;
    listen [::]:80;
    server_name docs.tokopawon.id;

    # Allow certbot renew via webroot
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    
    location /toko-pawon/v1 {
        alias /var/www/toko-pawon/docs/public;
    }

    location / {
        root /var/www/toko-pawon/docs/public;
    }

}

