site_name: Dokumentasi Toko Pawon
site_url: https://docs.pawon.cloud/toko-pawon/v1
theme:
  name: material
  language: id
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - image.zoom

nav:
  - Home: index.md
  - Admin Toko:
    - Login: admin/login.md
    - Pengaturan Ongkir (Pawon Logistik): admin/pengaturan-shipping.md
    - Pengaturan:
      - Saluran Penjualan: admin/pengaturan/saluran-penjualan.md
      - Lokasi & Pengiriman: admin/pengaturan/lokasi-dan-pengiriman.md
      - Wilayah: admin/pengaturan/wilayah.md
      - Wilayah Pajak: admin/pengaturan/wilayah-pajak.md
      - Jenis Produk: admin/pengaturan/jenis-produk.md
      - Tag Produk: admin/pengaturan/tag-produk.md
      - Toko: admin/pengaturan/toko.md
      - Pengguna: admin/pengaturan/pengguna.md
      - Profile: admin/pengaturan/profile.md
  - Manajemen Produk:
    - Manajemen:
      - Manajemen Produk: admin/produk/manage.md
      - Menambah Produk Baru: admin/produk/add.md
      - Menambah Produk Baru (Multi Varian): admin/produk/add-multi-variant.md
      - Detail Produk: admin/produk/detail-produk.md
    - Kategori Produk: admin/produk/kategori.md
    - Membuat Kategori: admin/produk/add-kategori.md
    - Detail Kategori: admin/produk/detail-kategori.md
    - Koleksi Produk: admin/produk/koleksi.md
  - Manajemen Pelanggan: 
    - Kelola Pelanggan: admin/pelanggan/manage.md